### ISSUE TITLE
Exposing more APIs

### ISSUE THREAD

**Issue by martinRenou** [jpbede/aioelectricitymaps#137]
Hello,

Thanks for this library! This is exactly what we are looking for.

Do you plan on exposing more [electricity maps APIs](https://static.electricitymaps.com/api/docs/index.html)? 

We could provide help on this if you'd like.

**Comment by jpbede** [comment]
Sure, I can add them

**Comment by jpbede** [comment]
Any specific endpoint you need?

**Comment by martinRenou** [comment]
Amazing thanks!

I guess we're only interested by the freely available endpoints for now, so:
- `/v3/carbon-intensity/history`
- `/v3/power-breakdown/latest`
- `/v3/power-breakdown/history`

**Comment by jpbede** [comment]
There you go https://github.com/jpbede/aioelectricitymaps/releases/tag/v1.0.0
v1.0.0 should be available on PyPi in a few minutes

**Comment by martinRenou** [comment]
That's great! We'll test it out right away
